"""Read ENA's run records into evidence files, for the files ENA itself generated (#606).

ENA writes a paired run's reads as ``<run_accession>_1.fastq.gz`` and ``_2`` ("Files
Generated by the Archive"), and its run record states the library: strategy, source,
platform and instrument. AnVIL datasets that copied those files keep ENA's names, and
no table of theirs states the library, so ENA's run record is the one source for it.

**The join is the md5, not the name** (contract 2.10). A file whose name fits ENA's convention
(:data:`GENERATED_FASTQ`) is looked up by the accession in it, and evidence is written
only where ENA's ``fastq_md5`` for the file of that name in that run equals the
catalog's ``file_md5sum``: then the file in AnVIL is ENA's file. A name match alone
writes nothing — a run ENA does not return, a run whose md5s cannot be paired with its
files, a name not among the run's files, an md5 that differs, and a catalog file with no
md5 are each counted (:class:`DatasetImport`)
and reported, never written.

**Lines are observations** (contract 1.1): one per ENA field in :data:`FIELD_SLOTS`,
transcribed verbatim under the slot the AnVIL slot map gives the same SRA column, keyed
by the file's ``file_id``. What a value means is the translation table's (#414). An
empty field is ENA's spelling of absent and writes nothing. ENA's other fields
(``library_construction_protocol`` among them) speak to no slot, and are kept only in
the stored response.

**The response is kept**: each generation holds the rows ENA returned for its
dataset's runs, as fetched, in :data:`RESPONSE_FILE` beside the evidence file, so an
import can be re-run from it without the network (:func:`load_response`).
``discover`` reads only ``*.ndjson``, so no evidence reader takes it as evidence.

**An import is a generation**, as the AnVIL importers' are, under
``ena/<catalog>/<dataset>/<generation>/``. A dataset with files named as ENA's but none
whose md5 matches fails the import rather than writing nothing quietly, as the AnVIL
importer fails a table that reaches no file: an evidence file with no lines is refused by
reconcile (contract 5.3), and no generation at all would leave an older one current.
"""

from __future__ import annotations

import json
import re
from collections import Counter
from collections.abc import Callable, Iterable, Iterator
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

import requests

from .anvil_evidence import chosen_datasets, verbatim_manifest
from .azul_manifest import REPOSITORY, VERBATIM_FILE, iter_verbatim_lines, parse_verbatim_line, sidecar_datasets
from .models import JOIN_KEY_FILE_ID, SOURCE_EXTERNAL_GROUND_TRUTH
from .schema.classification_model import ImporterSourceTypeEnum, JoinKeyEnum
from .source_evidence import (
    EvidenceEntry,
    EvidenceFileEnvelope,
    EvidenceFileSource,
    EvidenceTarget,
    claim_source_for,
    evidence_file_path,
    generation_dir,
    new_generation,
    staged_generation,
    write_evidence_file,
)

# The source's name: the evidence directory, the envelope's repository, and the
# `source` a translation row's scope names.
SOURCE = "ena"
# ENA's result type, as the portal API names it; the evidence file's table.
TABLE = "read_run"
PORTAL_SEARCH = "https://www.ebi.ac.uk/ena/portal/api/search"
# ENA's key for a run record, in its own name (the envelope's `source_key`).
SOURCE_KEY = "run_accession"
# A run accession of ENA, SRA or DDBJ; `validate_ena_accessions` finds one in a name by it.
RUN_ACCESSION = r"[ESD]RR\d{6,}"
# ENA's generated-FASTQ names: a run accession, the read of a pair or none, `.fastq.gz`.
GENERATED_FASTQ = re.compile(rf"^({RUN_ACCESSION})(?:_[12])?\.fastq\.gz$")
# ENA's fields and the slot each is written under, the slots the AnVIL slot map gives
# the same SRA columns of ANVIL_1000G_high_coverage_2019's `sample` table.
FIELD_SLOTS = {
    "library_strategy": "assay_type",
    "library_source": "data_modality",
    "instrument_platform": "platform",
    "instrument_model": "platform",
}
# What is asked of ENA: the key, the two lists the md5 check reads, the mapped fields,
# and the protocol, which no slot takes and the stored response keeps.
FIELDS = (SOURCE_KEY, "fastq_ftp", "fastq_md5", *FIELD_SLOTS, "library_construction_protocol")
RESPONSE_FILE = f"{TABLE}.response.json"
# Accessions per portal request; the request is a POST, so the list is not in a URL.
BATCH = 500


@dataclass(frozen=True)
class Response:
    """ENA's rows for one dataset's runs, keyed by run accession, and when they were asked for.

    ``catalog`` is the catalog whose files the runs were looked up for: a stored response is
    re-imported only against that catalog (:func:`import_dataset`).
    """

    catalog: str
    dataset: str
    requested_at: datetime
    rows: dict[str, dict]


Fetch = Callable[[str, str, list[str]], Response]


@dataclass(frozen=True)
class Candidate:
    """A catalog file named as ENA names a generated FASTQ."""

    file_id: str
    file_name: str
    md5: str | None
    accession: str


@dataclass
class DatasetImport:
    """One dataset's import: what matched, what did not and why, and where it went.

    ``outcomes`` counts every candidate file once: ``matched``, ``no_run`` (ENA returned
    no record for the accession), ``md5_unlisted`` (the run's file and md5 lists differ in
    length, so neither can be read), ``not_in_run`` (the run lists no file of that name),
    ``md5_differs``, and ``no_catalog_md5``.
    """

    dataset: str
    directory: Path
    outcomes: Counter = field(default_factory=Counter)
    written: int = 0


# --- the network --------------------------------------------------------------------


def fetch_runs(catalog: str, dataset: str, accessions: list[str]) -> Response:
    """ENA's ``read_run`` rows for ``accessions``, asked for :data:`BATCH` at a time over one session.

    A run ENA returns twice must be the same row both times, or this raises; a run it
    does not return is absent, which the import counts.
    """
    requested_at = datetime.now(timezone.utc)
    rows: dict[str, dict] = {}
    with requests.Session() as http:
        for start in range(0, len(accessions), BATCH):
            data = {
                "result": TABLE,
                "includeAccessions": ",".join(accessions[start : start + BATCH]),
                "fields": ",".join(FIELDS),
                "format": "json",
                "limit": 0,
            }
            response = http.post(PORTAL_SEARCH, data=data, timeout=300)
            response.raise_for_status()
            for row in response.json():
                add_row(rows, row, PORTAL_SEARCH)
    return Response(catalog=catalog, dataset=dataset, requested_at=requested_at, rows=rows)


def add_row(rows: dict[str, dict], row: object, where: str) -> None:
    """Add one ENA row to ``rows`` under its accession, refusing a malformed or contradicting one."""
    if not isinstance(row, dict) or not isinstance(row.get(SOURCE_KEY), str):
        raise ValueError(f"{where}: an ENA row without a {SOURCE_KEY}: {row!r}")
    accession = row[SOURCE_KEY]
    if accession in rows and rows[accession] != row:
        raise ValueError(f"{where}: ENA returned two different rows for {accession}")
    rows[accession] = row


# --- the stored response ------------------------------------------------------------


def write_response(path: Path, response: Response) -> None:
    """Write ``response`` as fetched: the catalog and dataset, the request time, and ENA's rows."""
    document = {
        "catalog": response.catalog,
        "dataset": response.dataset,
        "requested_at": response.requested_at.isoformat(),
        "url": PORTAL_SEARCH,
        "fields": list(FIELDS),
        "rows": [response.rows[a] for a in sorted(response.rows)],
    }
    path.write_text(json.dumps(document, indent=1, sort_keys=True) + "\n", encoding="utf-8")


def load_response(path: Path) -> Response:
    """A response :func:`write_response` stored, to import from without the network."""
    document = json.loads(path.read_text(encoding="utf-8"))
    rows: dict[str, dict] = {}
    for row in document["rows"]:
        add_row(rows, row, str(path))
    return Response(
        catalog=document["catalog"],
        dataset=document["dataset"],
        requested_at=datetime.fromisoformat(document["requested_at"]),
        rows=rows,
    )


# --- importing ----------------------------------------------------------------------


# A gate on the raw line, as `iter_verbatim_entities`' is: only a line naming a `.fastq.gz`
# is parsed, and the parsed type and `file_name` decide.
_LINE_GATE = '.fastq.gz"'


def candidates(path: Path) -> list[Candidate]:
    """The dataset's catalog files named as ENA names a generated FASTQ, from its verbatim manifest."""
    found = []
    for n, line in iter_verbatim_lines(path):
        if _LINE_GATE not in line:
            continue
        entity_type, value = parse_verbatim_line(path, n, line)
        name = value.get("file_name")
        if entity_type != VERBATIM_FILE or not isinstance(name, str):
            continue
        match = GENERATED_FASTQ.match(name)
        if match is None:
            continue
        file_id = value.get("file_id")
        if not isinstance(file_id, str) or not file_id:
            raise ValueError(f"{path}:{n}: {VERBATIM_FILE} {name!r} has no file_id to key its evidence by")
        md5 = value.get("file_md5sum")
        found.append(
            Candidate(
                file_id=file_id,
                file_name=name,
                md5=md5 if isinstance(md5, str) and md5 else None,
                accession=match.group(1),
            )
        )
    return found


def run_md5s(row: dict) -> dict[str, str] | None:
    """A run's generated files, by file name, to ENA's md5 of each; None where the two lists disagree.

    ``fastq_ftp`` and ``fastq_md5`` are parallel ``;``-separated lists. Read by name, not
    position: a paired run can list an unpaired file beside its two reads. Lists of
    different lengths cannot be paired, so no file of that run can be matched.
    """
    paths = [p for p in (row.get("fastq_ftp") or "").split(";") if p]
    md5s = [m for m in (row.get("fastq_md5") or "").split(";") if m]
    if len(paths) != len(md5s):
        return None
    return {p.rsplit("/", 1)[-1]: m for p, m in zip(paths, md5s, strict=True)}


def outcome(candidate: Candidate, rows: dict[str, dict]) -> str:
    """Why ``candidate`` is or is not ENA's file: ``matched`` or one of the counted misses."""
    if candidate.md5 is None:
        return "no_catalog_md5"
    row = rows.get(candidate.accession)
    if row is None:
        return "no_run"
    md5s = run_md5s(row)
    if md5s is None:
        return "md5_unlisted"
    md5 = md5s.get(candidate.file_name)
    if md5 is None:
        return "not_in_run"
    return "matched" if md5.lower() == candidate.md5.lower() else "md5_differs"


def entries(candidate: Candidate, row: dict, source: EvidenceFileSource) -> Iterator[EvidenceEntry]:
    """The lines one matched file receives: each non-empty mapped field, verbatim."""
    for column, slot in FIELD_SLOTS.items():
        raw = row.get(column)
        if not raw:
            continue
        yield EvidenceEntry(
            field=slot, target_key_value=candidate.file_id, raw_value=raw, source=claim_source_for(source, column)
        )


def import_all(
    manifest_root: Path,
    catalog: str,
    evidence_root: Path,
    fetch: Fetch = fetch_runs,
    datasets: Iterable[str] | None = None,
    generation: str | None = None,
) -> list[DatasetImport]:
    """Import every dataset of the catalog's sidecar (or ``datasets``), each as one new generation.

    A dataset with no file named as ENA names one is passed over with no request. The
    stamp is shared across the datasets of one run, as the AnVIL importer's is. Raises
    before writing anything if a chosen dataset's verbatim manifest cannot be read.
    """
    named = sidecar_datasets(manifest_root, catalog)
    chosen = chosen_datasets(list(named), None if datasets is None else list(datasets))
    found_paths = {dataset: verbatim_manifest(manifest_root, catalog, dataset, named) for dataset in chosen}
    problems = [path for path in found_paths.values() if isinstance(path, str)]
    if problems:
        raise ValueError("; ".join(problems))
    paths = {dataset: path for dataset, path in found_paths.items() if isinstance(path, Path)}
    stamp = generation or new_generation()
    imports = []
    for dataset, path in paths.items():
        found = candidates(path)
        if found:
            imports.append(import_dataset(dataset, found, catalog, evidence_root, fetch, stamp))
    return imports


def import_dataset(
    dataset: str,
    found: list[Candidate],
    catalog: str,
    evidence_root: Path,
    fetch: Fetch,
    generation: str,
) -> DatasetImport:
    """Look ``found``'s runs up and write one generation: the evidence file and ENA's response.

    Refuses a response for another catalog or dataset, so a stored one is imported only as
    what it was fetched for, and raises, writing nothing, when no file matched. The envelope's ``fetched_at`` is when ENA was
    asked, and its ``source_version`` that day: ENA publishes no version of its records.
    """
    # A file with no catalog md5 cannot match whatever ENA says, so its run is not asked for.
    response = fetch(catalog, dataset, sorted({c.accession for c in found if c.md5 is not None}))
    if (response.catalog, response.dataset) != (catalog, dataset):
        raise ValueError(
            f"a response for {response.catalog}/{response.dataset} cannot be imported as {catalog}/{dataset}"
        )
    result = DatasetImport(dataset, generation_dir(evidence_root, SOURCE, catalog, dataset, generation))
    matched = []
    for candidate in found:
        verdict = outcome(candidate, response.rows)
        result.outcomes[verdict] += 1
        if verdict == "matched":
            matched.append(candidate)
    if not matched:
        # As the AnVIL importer fails a mapped table that reaches no file: names that are
        # ENA's but files that are not is the source disagreeing with the catalog (contract
        # 5.3), and writing nothing quietly would leave an older generation current.
        counts = ", ".join(f"{verdict} {n:,}" for verdict, n in sorted(result.outcomes.items()))
        raise ValueError(f"{dataset}: no file named as ENA's matched ENA's md5 ({counts}); nothing written")
    source = EvidenceFileSource(repository=SOURCE, table=TABLE, url=PORTAL_SEARCH)
    envelope = EvidenceFileEnvelope(
        source=source,
        source_type=ImporterSourceTypeEnum(SOURCE_EXTERNAL_GROUND_TRUTH),
        source_version=response.requested_at.date().isoformat(),
        source_key=SOURCE_KEY,
        target=EvidenceTarget(system=REPOSITORY, dataset=dataset, version=catalog),
        target_key=JoinKeyEnum(JOIN_KEY_FILE_ID),
        fetched_at=response.requested_at.isoformat(),
    )
    lines = (e for c in matched for e in entries(c, response.rows[c.accession], source))
    with staged_generation(result.directory) as staging:
        result.written = write_evidence_file(evidence_file_path(staging, TABLE), envelope, lines)
        if not result.written:
            # Matched files whose every mapped field is empty: an evidence file with no
            # lines is refused by reconcile (contract 5.3), so fail as no match does.
            raise ValueError(f"{dataset}: {len(matched):,} matched files, but ENA states no mapped field for any")
        write_response(staging / RESPONSE_FILE, response)
    return result


def describe(imports: list[DatasetImport]) -> list[str]:
    """One line per dataset: where it went, then each outcome's count."""
    lines = []
    for run in imports:
        lines.append(
            f"{run.dataset} -> {run.directory} ({run.outcomes.total():,} files named as ENA's, {run.written:,} lines)"
        )
        for verdict, n in sorted(run.outcomes.items()):
            lines.append(f"  {verdict}: {n:,}")
    return lines
