"""The manifest survey (issue #384): absence, the entity census, the two reach
traversals that disagree, the readiness bands, and the contradictions it records —
against synthetic manifests small enough to reason about, plus the script's
refusal to survey an incomplete set."""

import json
import re
import sys
from pathlib import Path

import pytest

from meta_disco import manifest_survey as ms
from meta_disco.azul_manifest import (
    FORMAT_COMPACT,
    FORMAT_VERBATIM,
    iter_verbatim_entities,
    manifest_dir,
    manifest_path,
    save_sidecar,
)
from meta_disco.models import CLASSIFICATION_FIELDS
from meta_disco.schema_vocab import dimension_values

sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))

import generate_manifest_survey as cli

CATALOG = "anvil15"

COMPACT_COLUMNS = [
    "datasets.consent_group",
    "datasets.data_use_permission",
    "datasets.registered_identifier",
    "donors.donor_id",
    "donors.phenotypic_sex",
    "donors.reported_ethnicity",
    "donors.genetic_ancestry",
    "biosamples.biosample_id",
    "biosamples.anatomical_site",
    "biosamples.biosample_type",
    "activities.activity_id",
    "activities.assay_type",
    "files.file_id",
    "files.data_modality",
]


def compact_path(root: Path, title: str = "D") -> Path:
    """One dataset's compact manifest, located the way the survey locates it.

    Through ``azul_manifest`` rather than by re-spelling ``manifest/<catalog>/``:
    the layout reorg in #268/#269 moves these directories, and a test that spells
    them itself is the thing that breaks when it lands.
    """
    return manifest_path(root, CATALOG, title, FORMAT_COMPACT)


def verbatim_path(root: Path, title: str = "D") -> Path:
    return manifest_path(root, CATALOG, title, FORMAT_VERBATIM)


def write_manifests(root: Path, title: str, compact: list[dict], verbatim: list[tuple[str, dict]]) -> None:
    """Put one dataset's two manifests on disk in the layout the survey reads."""
    manifest_dir(root, CATALOG).mkdir(parents=True, exist_ok=True)
    lines = ["\t".join(COMPACT_COLUMNS)]
    lines += ["\t".join(str(row.get(column, "")) for column in COMPACT_COLUMNS) for row in compact]
    compact_path(root, title).write_text("\n".join(lines) + "\n")
    verbatim_path(root, title).write_text(
        "".join(json.dumps({"type": entity_type, "value": value}) + "\n" for entity_type, value in verbatim)
    )


def write_sidecar(root: Path, counts: dict[str, int]) -> None:
    save_sidecar(root, CATALOG, {"catalog": CATALOG, "datasets": {t: {"file_count": n} for t, n in counts.items()}})


def anvil_file(file_id: str, name: str = "", drs: str | None = None) -> tuple[str, dict]:
    value = {"file_id": file_id, "file_name": name or f"{file_id}.bam"}
    if drs is not None:
        value["drs_uri"] = f"drs://drs.anv0:v2_{drs}"
    return "anvil_file", value


def activity(used: list[str], generated: list[str], biosamples: list[str] | None = None) -> tuple[str, dict]:
    return "anvil_activity", {
        "activity_id": f"act-{'-'.join(generated) or 'none'}",
        "used_file_id": used,
        "generated_file_id": generated,
        "used_biosample_id": biosamples or [],
    }


def donor_chain() -> list[tuple[str, dict]]:
    """Three files where only the first is a hop from a donor.

    ``fastq`` is generated by an activity that used ``bs1``, ``bam`` is generated
    from ``fastq``, and ``orphan`` is generated by nothing — so single hop reaches
    one file, transitive closure reaches two, and neither reaches three.
    """
    return [
        anvil_file("fastq"),
        anvil_file("bam"),
        anvil_file("orphan"),
        ("anvil_biosample", {"biosample_id": "bs1", "donor_id": ["dn1"]}),
        activity(used=[], generated=["fastq"], biosamples=["bs1"]),
        activity(used=["fastq"], generated=["bam"]),
    ]


JOINED_ROW = {"donors.donor_id": "dn1", "biosamples.biosample_id": "bs1", "activities.activity_id": "ac1"}

UUID_A = "aaaaaaaa-1111-2222-3333-444444444444"
UUID_B = "bbbbbbbb-1111-2222-3333-444444444444"


# --- absence ------------------------------------------------------------------


@pytest.mark.parametrize("cell", ["", "  ", "null", "NULL", "NA", "n/a", "None", "[]", "{}"])
def test_absent_spellings_are_absent(cell):
    assert ms.cell_absent(cell)


@pytest.mark.parametrize("cell", ["0", "false", "NRES", "GRCh38", "nan"])
def test_values_are_not_absent(cell):
    assert not ms.cell_absent(cell)


def test_zero_and_false_are_values_not_gaps():
    # A coverage of 0.0 or a has_replicates of false is data the submitter
    # recorded; only nothing is nothing.
    assert ms._is_filled(0)
    assert ms._is_filled(False)
    assert not ms._is_filled(None)
    assert not ms._is_filled([])
    assert not ms._is_filled("  ")


def test_compact_fill_counts_and_spelling_census(tmp_path):
    write_manifests(
        tmp_path,
        "D",
        [
            {"donors.donor_id": "d1", "files.file_id": "f1", "datasets.consent_group": "NRES"},
            {"donors.donor_id": "NA", "files.file_id": "f2", "datasets.consent_group": "NRES"},
            {"donors.donor_id": "", "files.file_id": "f3", "datasets.consent_group": "NRES"},
        ],
        [],
    )
    rows, columns, spellings = ms.survey_compact(compact_path(tmp_path))
    assert rows == 3
    by_name = {c.column: c for c in columns}
    assert by_name["donors.donor_id"].filled == 1
    assert by_name["files.file_id"].rate == 1.0
    # Both the empty cell and the literal NA are counted, under their own spellings.
    assert spellings["na"] == 1
    assert spellings["(empty)"] >= 1


def test_join_counts_come_from_the_column_coverage(tmp_path):
    # The three JOIN_* columns are counted once, with every other column; nothing
    # keeps a second tally of them.
    write_manifests(
        tmp_path,
        "D",
        [
            {"donors.donor_id": "dn1", "biosamples.biosample_id": "bs1", "activities.activity_id": "ac1"},
            {"donors.donor_id": "", "biosamples.biosample_id": "", "activities.activity_id": ""},
        ],
        [anvil_file("f1")],
    )
    write_sidecar(tmp_path, {"D": 1})
    dataset = ms.run_survey(tmp_path, CATALOG).datasets[0]
    assert dataset.filled(ms.JOIN_DONOR) == 1
    assert dataset.filled("donors.donor_id") == 1
    assert dataset.filled("no.such.column") == 0
    assert dataset.join_uniform


def test_join_uniform_is_false_when_a_column_lags(tmp_path):
    write_manifests(
        tmp_path,
        "D",
        [
            {"donors.donor_id": "dn1", "biosamples.biosample_id": "bs1", "activities.activity_id": "ac1"},
            {"donors.donor_id": "dn2", "biosamples.biosample_id": "bs2"},
        ],
        [anvil_file("f1")],
    )
    write_sidecar(tmp_path, {"D": 1})
    dataset = ms.run_survey(tmp_path, CATALOG).datasets[0]
    assert not dataset.join_uniform
    assert ms.join_uniform([dataset]) == []


# --- the entity census --------------------------------------------------------


def test_census_separates_submitter_tables_from_harmonized(tmp_path):
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "f1"}],
        [
            anvil_file("f1"),
            ("hifi", {"hifi_id": "x", "instrument_model": "Revio", "coverage": None}),
            ("hifi", {"hifi_id": "y", "instrument_model": "", "coverage": 30.0}),
        ],
    )
    tables, _reach, _files = ms.survey_verbatim(verbatim_path(tmp_path))
    by_name = {t.name: t for t in tables}
    assert by_name["anvil_file"].is_submitter is False
    hifi = by_name["hifi"]
    assert hifi.is_submitter and hifi.rows == 2
    assert hifi.fields["hifi_id"] == 2
    assert hifi.fields["instrument_model"] == 1  # the empty string is not a value
    assert hifi.fields["coverage"] == 1  # 30.0 counts, None does not


def test_census_keeps_a_field_that_is_never_filled(tmp_path):
    # `platform` is on every row of both tables and filled on none. It is kept at
    # 0% rather than dropped, and still carries no dimension: a column the header
    # promises is not one a consumer (#369) could read.
    write_sidecar(tmp_path, {"D": 1})
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "f1"}],
        [
            anvil_file("f1"),
            ("prep", {"prep_id": "x", "platform": ""}),
            ("prep", {"prep_id": "y", "platform": None}),
            ("probe", {"platform": ""}),
        ],
    )
    tables, _reach, _files = ms.survey_verbatim(verbatim_path(tmp_path))
    by_name = {t.name: t for t in tables}
    assert by_name["prep"].fields == {"prep_id": 2, "platform": 0}
    assert by_name["prep"].filled_fields == [("prep_id", 2)]
    assert by_name["prep"].never_filled_fields == ["platform"]
    assert by_name["prep"].dimension_fields == []
    report = ms.render_report(ms.run_survey(tmp_path, CATALOG))
    assert "- **`prep`** (2 rows): `prep_id` 100%" in report
    assert "  - never filled (1): `platform`" in report
    # A table whose every field is empty still gets a line, and says so.
    assert "- **`probe`** (1 row): no field is filled on any row" in report


def test_table_name_encodes_dimensions():
    # `chains` names a real content kind the schema has no term for: the dimension
    # is recorded, the value is null, and nothing is invented to fill it.
    assert ms._table_encodes("chains_to_chm13_mc") == [
        ("data_type", None),
        ("reference_assembly", "CHM13"),
    ]
    assert ("platform", "ONT") in ms._table_encodes("ont_methylation")
    assert ms._table_encodes("participant") == []
    # An ambiguous name keeps both references rather than picking one.
    encoded = ms._table_encodes("chm13_vs_grch38")
    assert ("reference_assembly", "CHM13") in encoded
    assert ("reference_assembly", "GRCh38") in encoded


def test_name_token_values_are_schema_vocabulary():
    """Every term this survey publishes must be one classification.yaml defines.

    The survey exists to be consumed by #369; a value it invented would be one
    #369 then had to translate. Mirrors tests/test_rule_vocabulary.py, which
    holds the rule engine to the same schema.
    """
    for token, (dimension, value) in ms.NAME_TOKENS.items():
        assert dimension in CLASSIFICATION_FIELDS, f"{token} names a dimension that does not exist"
        if value is not None:
            assert value in dimension_values(dimension), f"{token} -> {value!r} is not in {dimension}_enum"


def test_field_token_dimensions_are_real_dimensions():
    for name, dimension in ms.FIELD_TOKENS.items():
        assert dimension in CLASSIFICATION_FIELDS, f"{name} names a dimension that does not exist"


def test_vocabulary_gaps_are_reported_not_hidden(tmp_path):
    write_sidecar(tmp_path, {"D": 1})
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "f1"}],
        [anvil_file("f1"), ("chains_to_chm13_mc", {"chain_id": "c", "path": "f1"})],
    )
    report = ms.render_report(ms.run_survey(tmp_path, CATALOG))
    assert "Table names the vocabulary cannot express" in report
    assert "`chains`" in report
    assert ms.NO_VOCABULARY_TERM in report


def test_no_vocabulary_gap_section_when_every_token_maps(tmp_path):
    write_sidecar(tmp_path, {"D": 1})
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "f1"}],
        [anvil_file("f1"), ("assembly", {"assembly_id": "a", "path": "f1"})],
    )
    report = ms.render_report(ms.run_survey(tmp_path, CATALOG))
    assert "Table names the vocabulary cannot express" not in report


def test_dimension_fields_need_to_be_populated(tmp_path):
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "f1"}],
        [
            anvil_file("f1"),
            ("submitted", {"reference_assembly": "GRCh38", "platform": None, "assembly_date": "2024-09"}),
        ],
    )
    tables, _reach, _files = ms.survey_verbatim(verbatim_path(tmp_path))
    table = next(t for t in tables if t.name == "submitted")
    # reference_assembly is filled and counts; platform is present but empty and
    # does not; assembly_date is not a dimension field despite the prefix.
    assert table.dimension_fields == [("reference_assembly", "reference_assembly")]
    assert table.carries_dimension


# --- file identity ------------------------------------------------------------


def test_file_keys_index_drs_uuid_distinct_from_file_id():
    keys = ms.FileKeys()
    keys.add({"file_id": "azul-1", "file_name": "a.bam", "drs_uri": f"drs://drs.anv0:v2_{UUID_A}"})
    resolved = keys.resolved()
    # ENCORE's shape: the submitter names the DRS object, not Azul's file id.
    assert resolved[UUID_A] == "azul-1"
    assert resolved["azul-1"] == "azul-1"
    assert resolved["a.bam"] == "azul-1"


def test_file_keys_drop_a_name_two_files_share():
    keys = ms.FileKeys()
    keys.add({"file_id": "one", "file_name": "same.bam"})
    keys.add({"file_id": "two", "file_name": "same.bam"})
    keys.add({"file_id": "three", "file_name": "unique.bam"})
    resolved = keys.resolved()
    assert "same.bam" not in resolved
    assert resolved["unique.bam"] == "three"


def test_submitter_table_names_files_through_a_drs_uri(tmp_path):
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "azul-1"}],
        [
            anvil_file("azul-1", "a.bam", drs=UUID_A),
            anvil_file("azul-2", "b.bam", drs=UUID_B),
            ("hifi", {"hifi_id": "s1", "path": f"drs://drs.anv0:v2_{UUID_A}"}),
            # A uuid that is not one of this dataset's files must not count.
            ("hifi", {"hifi_id": "s2", "path": "drs://drs.anv0:v2_cccccccc-1111-2222-3333-444444444444"}),
        ],
    )
    tables, _reach, dimension_files = ms.survey_verbatim(verbatim_path(tmp_path))
    assert next(t for t in tables if t.name == "hifi").files_named == 1
    assert dimension_files == 1


def test_dimension_files_are_a_union_not_a_sum(tmp_path):
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "f1"}],
        [
            anvil_file("f1", "a.bam"),
            ("hifi", {"hifi_id": "s", "path": "f1"}),
            ("assembly", {"assembly_id": "s", "assembly": "f1"}),
        ],
    )
    _tables, _reach, dimension_files = ms.survey_verbatim(verbatim_path(tmp_path))
    # Both tables name the same one file; summing them would say two.
    assert dimension_files == 1


# --- reach --------------------------------------------------------------------


def test_single_hop_and_transitive_reach_disagree_on_a_chain(tmp_path):
    # biosample -> fastq (generated by an activity that names it)
    #           -> bam   (generated by an activity that used the fastq only)
    # Single hop reaches the fastq; transitive closure reaches both. This is the
    # 1000G shape in miniature.
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "fastq"}, {"files.file_id": "bam"}],
        [
            anvil_file("fastq"),
            anvil_file("bam"),
            ("anvil_biosample", {"biosample_id": "bs1", "donor_id": ["dn1"]}),
            activity(used=[], generated=["fastq"], biosamples=["bs1"]),
            activity(used=["fastq"], generated=["bam"]),
        ],
    )
    _tables, reach, _files = ms.survey_verbatim(verbatim_path(tmp_path))
    assert reach.files == 2
    assert reach.single_hop_donor == 1
    assert reach.transitive_donor == 2


def test_a_biosample_without_a_donor_reaches_a_biosample_only(tmp_path):
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "f1"}],
        [
            anvil_file("f1"),
            ("anvil_biosample", {"biosample_id": "bs1", "donor_id": []}),
            activity(used=[], generated=["f1"], biosamples=["bs1"]),
        ],
    )
    _tables, reach, _files = ms.survey_verbatim(verbatim_path(tmp_path))
    assert reach.single_hop_biosample == 1
    assert reach.single_hop_donor == 0
    assert reach.transitive_biosample == 1
    assert reach.transitive_donor == 0


def test_a_file_no_activity_mentions_reaches_nothing(tmp_path):
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "f1"}],
        [anvil_file("f1"), ("anvil_biosample", {"biosample_id": "bs1", "donor_id": ["dn1"]})],
    )
    _tables, reach, _files = ms.survey_verbatim(verbatim_path(tmp_path))
    assert reach.transitive_donor == 0
    assert reach.single_hop_donor == 0


def test_components_merge_when_a_later_activity_joins_them(tmp_path):
    # The activity naming the biosample is seen first, and only the last activity
    # connects "late" to it. A mark applied before that union must still count.
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "early"}, {"files.file_id": "late"}],
        [
            anvil_file("early"),
            anvil_file("late"),
            ("anvil_biosample", {"biosample_id": "bs1", "donor_id": ["dn1"]}),
            activity(used=[], generated=["early"], biosamples=["bs1"]),
            activity(used=["early"], generated=["late"]),
        ],
    )
    _tables, reach, _files = ms.survey_verbatim(verbatim_path(tmp_path))
    assert reach.transitive_donor == 2


# --- readiness ----------------------------------------------------------------


@pytest.mark.parametrize(
    ("rate", "verdict"),
    [(1.0, "yes"), (ms.READY_HIGH, "yes"), (ms.READY_HIGH - 0.01, "partial"), (ms.READY_LOW, "partial"), (0.0, "no")],
)
def test_verdict_bands(rate, verdict):
    assert ms._verdict(rate) == verdict


def test_readiness_reports_the_number_behind_each_verdict(tmp_path):
    survey = surveyed(tmp_path)
    verdicts = ms.readiness(survey.datasets[0])
    assert verdicts["governance"][0] == "yes"
    assert "consent/DUO 100%" in verdicts["governance"][1]
    assert verdicts["edges"][0] == "yes"
    # The denominator is named, because the dimensions verdict uses a different one.
    assert "2 of 2 compact rows" in verdicts["edges"][1]
    assert "verbatim files" in verdicts["dimensions"][1]


def test_edges_verdict_rests_on_the_join_not_the_upper_bound(tmp_path):
    """The transitive walk is an upper bound, so it informs but does not decide.

    Here the compact join reaches one file of four and the transitive walk
    reaches two. The verdict follows the join (25%, partial), and the transitive
    figure is reported beside it rather than promoting the dataset.
    """
    write_sidecar(tmp_path, {"D": 4})
    write_manifests(
        tmp_path,
        "D",
        [{"donors.donor_id": "dn1", "biosamples.biosample_id": "bs1", "activities.activity_id": "ac1"}]
        + [{"files.file_id": f"f{i}"} for i in range(3)],
        [
            anvil_file("fastq"),
            anvil_file("bam"),
            anvil_file("spare1"),
            anvil_file("spare2"),
            ("anvil_biosample", {"biosample_id": "bs1", "donor_id": ["dn1"]}),
            activity(used=[], generated=["fastq"], biosamples=["bs1"]),
            activity(used=["fastq"], generated=["bam"]),
        ],
    )
    dataset = ms.run_survey(tmp_path, CATALOG).datasets[0]
    assert dataset.filled(ms.JOIN_DONOR) == 1
    assert dataset.reach.transitive_donor == 2
    verdict, basis = ms.readiness(dataset)["edges"]
    assert verdict == "partial"  # 1 of 4, not 2 of 4
    assert "1 of 4 compact rows (25%)" in basis
    assert "verbatim transitive 50%" in basis


# --- end to end ---------------------------------------------------------------


def surveyed(root: Path) -> ms.Survey:
    """A one-dataset survey whose every dimension is exercised by the assertions above."""
    write_sidecar(root, {"D": 2})
    write_manifests(
        root,
        "D",
        [
            {
                "datasets.consent_group": "NRES",
                "datasets.data_use_permission": "NRES",
                "donors.donor_id": "dn1",
                "donors.phenotypic_sex": "XX",
                "biosamples.biosample_id": "bs1",
                "files.file_id": "fastq",
            },
            {
                "datasets.consent_group": "NRES",
                "datasets.data_use_permission": "NRES",
                "donors.donor_id": "dn1",
                "donors.phenotypic_sex": "XX",
                "biosamples.biosample_id": "bs1",
                "files.file_id": "bam",
            },
        ],
        [
            anvil_file("fastq"),
            anvil_file("bam"),
            ("anvil_biosample", {"biosample_id": "bs1", "donor_id": ["dn1"]}),
            activity(used=[], generated=["fastq"], biosamples=["bs1"]),
            activity(used=["fastq"], generated=["bam"]),
            ("hifi", {"hifi_id": "s", "path": "fastq"}),
        ],
    )
    return ms.run_survey(root, CATALOG)


def test_run_survey_totals_against_the_sidecar(tmp_path):
    survey = surveyed(tmp_path)
    assert survey.measured_total == 2
    assert survey.snapshot_total == 2
    assert survey.datasets[0].compact_rows == 2


def test_contradiction_records_the_traversal_not_the_manifest(tmp_path):
    found = ms.contradictions(surveyed(tmp_path))
    traversal = [c for c in found if "#337" in c[0]]
    assert len(traversal) == 1
    assert "Single hop reaches 1 file of 2" in traversal[0][2]  # not "1 files"
    assert "transitive closure over the same activities reaches 2 (100%)" in traversal[0][2]
    # Each count against the denominator it was taken against, so the evidence
    # shown is the evidence the comparison used.
    assert "the compact join's 2 of 2 compact rows (100%)" in traversal[0][2]


def test_contradiction_records_the_brief_where_a_field_is_populated(tmp_path):
    found = ms.contradictions(surveyed(tmp_path))
    brief = [c for c in found if "comparability-gap" in c[0]]
    assert len(brief) == 1
    assert "donor sex 100% in D" in brief[0][2]


def test_brief_ancestry_claim_checks_both_spellings(tmp_path):
    # The brief says "ancestry" and the compact manifest spells it two ways. A
    # value in either one contradicts the claim, and the message says which.
    write_sidecar(tmp_path, {"D": 1})
    write_manifests(tmp_path, "D", [{"donors.genetic_ancestry": "EUR"}], [anvil_file("f1")])
    found = ms.contradictions(ms.run_survey(tmp_path, CATALOG))
    brief = [c for c in found if "comparability-gap" in c[0]]
    assert len(brief) == 1
    assert "donor genetic ancestry 100% in D" in brief[0][2]
    assert "reported ethnicity" not in brief[0][2]


def test_contradiction_records_the_join_arriving_whole(tmp_path):
    # #384's body reports HPRC_R2 at 91% donor/biosample but 23% activity. If the
    # three columns are filled together, that figure came from somewhere else.
    write_sidecar(tmp_path, {"AnVIL_HPRC_R2": 2})
    write_manifests(
        tmp_path,
        "AnVIL_HPRC_R2",
        [
            {"donors.donor_id": "dn1", "biosamples.biosample_id": "bs1", "activities.activity_id": "ac1"},
            {"files.file_id": "f2"},
        ],
        [anvil_file("f1"), anvil_file("f2")],
    )
    found = ms.contradictions(ms.run_survey(tmp_path, CATALOG))
    join = [c for c in found if "compact join" in c[1]]
    assert len(join) == 1
    assert "the same share as donor and biosample" in join[0][2]


def test_no_join_contradiction_when_the_columns_do_come_apart(tmp_path):
    write_sidecar(tmp_path, {"AnVIL_HPRC_R2": 2})
    write_manifests(
        tmp_path,
        "AnVIL_HPRC_R2",
        [
            {"donors.donor_id": "dn1", "biosamples.biosample_id": "bs1", "activities.activity_id": "ac1"},
            {"donors.donor_id": "dn2", "biosamples.biosample_id": "bs2"},
        ],
        [anvil_file("f1"), anvil_file("f2")],
    )
    found = ms.contradictions(ms.run_survey(tmp_path, CATALOG))
    assert [c for c in found if "compact join" in c[1]] == []


def test_a_claim_about_a_dataset_survives_a_recased_title(tmp_path):
    # The corpus carries both ANVIL_ and AnVIL_ prefixes, so an exact-case lookup
    # is a check that silently stops running if the catalog re-cases a title.
    write_sidecar(tmp_path, {"ANVIL_HPRC_r2": 2})
    write_manifests(
        tmp_path,
        "ANVIL_HPRC_r2",
        [
            {"donors.donor_id": "dn1", "biosamples.biosample_id": "bs1", "activities.activity_id": "ac1"},
            {"files.file_id": "f2"},
        ],
        [anvil_file("f1"), anvil_file("f2")],
    )
    found = ms.contradictions(ms.run_survey(tmp_path, CATALOG))
    assert [c for c in found if "compact join" in c[1]] != []


def test_every_prior_claim_declares_a_source_and_a_check():
    # A claim is a row in PRIOR_CLAIMS, so adding or retiring one is data.
    assert ms.PRIOR_CLAIMS
    for prior in ms.PRIOR_CLAIMS:
        assert prior.source and prior.claim
        assert callable(prior.check)


def test_no_contradiction_when_nothing_disagrees(tmp_path):
    write_sidecar(tmp_path, {"D": 1})
    write_manifests(tmp_path, "D", [{"files.file_id": "f1"}], [anvil_file("f1")])
    assert ms.contradictions(ms.run_survey(tmp_path, CATALOG)) == []


def test_table_separator_cells_are_three_characters(tmp_path):
    # Some markdown parsers require at least three dashes in a delimiter cell.
    lines = ms.render_report(surveyed(tmp_path)).splitlines()
    rules = [line for line in lines if set(line) <= set("|-: ") and "-" in line]
    assert rules
    for rule in rules:
        for cell in rule.strip("|").split("|"):
            assert len(cell.strip()) >= 3, rule


def test_report_renders_and_escapes_a_pipe_in_a_title(tmp_path):
    write_sidecar(tmp_path, {"a|b": 1})
    write_manifests(tmp_path, "a|b", [{"files.file_id": "f1"}], [anvil_file("f1")])
    report = ms.render_report(ms.run_survey(tmp_path, CATALOG))
    assert "a\\|b" in report
    # An unescaped pipe would close its cell, leaving the row a column short.
    lines = report.splitlines()
    header = next(i for i, line in enumerate(lines) if line.startswith("| key |"))
    title_row = next(line for line in lines[header:] if "a\\|b" in line)
    cells = lambda row: len(re.split(r"(?<!\\)\|", row))  # noqa: E731 — an escaped pipe is not a cell break
    assert cells(title_row) == cells(lines[header])


def test_survey_data_carries_the_unrounded_numbers(tmp_path):
    data = ms.survey_data(surveyed(tmp_path))
    dataset = data["datasets"]["D"]
    assert dataset["reach"]["single_hop_donor"] == 1
    assert dataset["reach"]["transitive_donor"] == 2
    assert dataset["compact_columns"]["donors.donor_id"]["rate"] == 1.0
    assert dataset["readiness"]["edges"]["verdict"] == "yes"


# --- the script ---------------------------------------------------------------


def test_script_writes_both_outputs(tmp_path, monkeypatch, capsys):
    surveyed(tmp_path)
    report, sidecar = tmp_path / "out.md", tmp_path / "out.json"
    monkeypatch.setattr(
        sys,
        "argv",
        ["generate_manifest_survey.py", "--data-dir", str(tmp_path), "--output", str(report), "--json", str(sidecar)],
    )
    assert cli.main() == 0
    assert "# What the AnVIL manifests carry" in report.read_text()
    assert json.loads(sidecar.read_text())["catalog"] == CATALOG


def test_script_refuses_an_incomplete_set_and_names_what_is_missing(tmp_path, monkeypatch, capsys):
    surveyed(tmp_path)
    (verbatim_path(tmp_path)).unlink()
    monkeypatch.setattr(sys, "argv", ["generate_manifest_survey.py", "--data-dir", str(tmp_path)])
    assert cli.main() == 1
    assert "D.verbatim.jsonl" in capsys.readouterr().err


def test_script_refuses_an_empty_sidecar(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(sys, "argv", ["generate_manifest_survey.py", "--data-dir", str(tmp_path)])
    assert cli.main() == 1
    err = capsys.readouterr().err
    assert "names no datasets" in err
    # Not smuggled through the missing-manifest list, which would have claimed
    # one manifest was named when none was.
    assert "manifest(s) named in the sidecar" not in err
    assert ms.sidecar_is_empty(tmp_path, CATALOG)


def test_percentages_do_not_round_to_a_misleading_100_or_0():
    # 100 means complete and 0 means none; anything else must look like neither.
    assert ms._pct(1.0) == "100"
    assert ms._pct(0.9957) == ">99"
    assert ms._pct(0.0) == "0"
    assert ms._pct(0.0005) == "<1"
    assert ms._pct(0.91) == "91"


def test_a_manifest_with_no_rows_still_reports_its_columns(tmp_path):
    # A header and no data rows: the columns exist and are 0% filled, which is a
    # different statement from the dataset having no columns at all.
    manifest_dir(tmp_path, CATALOG).mkdir(parents=True, exist_ok=True)
    compact_path(tmp_path).write_text("\t".join(COMPACT_COLUMNS) + "\n")
    rows, columns, _spellings = ms.survey_compact(compact_path(tmp_path))
    assert rows == 0
    assert [c.column for c in columns] == COMPACT_COLUMNS
    assert all(c.filled == 0 and c.rate == 0.0 for c in columns)


def test_a_short_compact_row_is_refused_before_it_can_be_mapped(tmp_path):
    # This used to reach record_from_compact_row and surface as int(None) on
    # file_size. iter_compact_rows refuses the row first now (#387), so the error
    # names the line for a better reason — the mapper never sees a None.
    from meta_disco.azul_manifest import iter_compact_records

    manifest_dir(tmp_path, CATALOG).mkdir(parents=True, exist_ok=True)
    header = ["files.document_id", "files.file_id", "files.file_name", "files.file_format", "files.file_size"]
    compact_path(tmp_path).write_text("\t".join(header) + "\nd1\tf1\ta.bam\tBAM\n")
    expected = re.escape("line 2: 4 fields for a 5-column header, missing files.file_size")
    with pytest.raises(ValueError, match=expected):
        list(iter_compact_records(compact_path(tmp_path)))


def test_compact_row_with_surplus_fields_names_the_line(tmp_path):
    manifest_dir(tmp_path, CATALOG).mkdir(parents=True, exist_ok=True)
    compact_path(tmp_path).write_text("a\tb\n1\t2\n1\t2\t3\n")
    with pytest.raises(ValueError, match="line 3"):
        ms.survey_compact(compact_path(tmp_path))


def test_compact_row_with_missing_fields_names_the_line_and_the_columns(tmp_path):
    # The mirror of the surplus case. A short row is a malformed manifest, not a
    # row with absent cells: Azul writes every column, and an absent value is
    # written as the empty string. Refusing it here is what lets every cell be
    # typed `str` (#387).
    manifest_dir(tmp_path, CATALOG).mkdir(parents=True, exist_ok=True)
    compact_path(tmp_path).write_text("a\tb\tc\n1\t2\t3\n4\t5\n")
    with pytest.raises(ValueError, match="line 3: 2 fields for a 3-column header, missing c"):
        ms.survey_compact(compact_path(tmp_path))


def test_a_separators_only_line_is_a_full_row_not_a_short_one(tmp_path):
    # It parses as width empty cells, so it is yielded and counted like any other
    # row. Pinned because the guard's docstring turns on the distinction: only a
    # line with *fewer* separators than the header is short.
    manifest_dir(tmp_path, CATALOG).mkdir(parents=True, exist_ok=True)
    compact_path(tmp_path).write_text("a\tb\tc\n1\t2\t3\n\t\t\n")
    rows, _columns, spellings = ms.survey_compact(compact_path(tmp_path))
    assert rows == 2
    assert spellings["(empty)"] == 3


def test_a_short_row_of_one_field_says_field_not_fields(tmp_path):
    manifest_dir(tmp_path, CATALOG).mkdir(parents=True, exist_ok=True)
    compact_path(tmp_path).write_text("a\tb\tc\n1\n")
    with pytest.raises(ValueError, match="line 2: 1 field for a 3-column header, missing b, c"):
        ms.survey_compact(compact_path(tmp_path))


def test_compact_line_numbers_survive_a_blank_line(tmp_path):
    # A blank line is dropped by csv.DictReader before the width guard sees it,
    # so it neither raises nor is yielded — but the row after it is still on its
    # own file line, which is the number the error has to name.
    manifest_dir(tmp_path, CATALOG).mkdir(parents=True, exist_ok=True)
    compact_path(tmp_path).write_text("a\tb\tc\n1\t2\t3\n\n4\t5\n")
    with pytest.raises(ValueError, match="line 4: 2 fields for a 3-column header, missing c"):
        ms.survey_compact(compact_path(tmp_path))


def test_a_scalar_where_an_id_list_belongs_raises(tmp_path):
    # Python would iterate a bare string character by character, unioning
    # single-character ids into the graph and corrupting the reach numbers.
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": "f1"}],
        [anvil_file("f1"), ("anvil_activity", {"activity_id": "a", "generated_file_id": "f1"})],
    )
    with pytest.raises(ValueError, match="generated_file_id is str"):
        ms.survey_verbatim(verbatim_path(tmp_path))


def test_no_traversal_contradiction_when_transitive_still_falls_short(tmp_path):
    # Single hop < transitive, but transitive < the compact join: the prior claim
    # holds here, so publishing a refutation would be wrong.
    write_sidecar(tmp_path, {"D": 3})
    write_manifests(tmp_path, "D", [JOINED_ROW] * 3, donor_chain())
    survey = ms.run_survey(tmp_path, CATALOG)
    dataset = survey.datasets[0]
    assert dataset.reach.single_hop_donor == 1 < dataset.reach.transitive_donor == 2
    assert dataset.filled(ms.JOIN_DONOR) == 3  # the compact join still reaches further
    assert [c for c in ms.contradictions(survey) if "#337" in c[0]] == []


def test_traversal_contradiction_compares_rates_not_raw_counts(tmp_path):
    # Six compact rows over three files: the compact join is filled on half its
    # rows, the transitive walk reaches two of three files. By raw count the walk
    # (2) looks weaker than the join (3) and the refutation would be suppressed;
    # each against its own denominator, 67% beats 50% and the refutation holds.
    write_sidecar(tmp_path, {"D": 3})
    spare = [{"files.file_id": f"f{i}"} for i in range(3)]
    write_manifests(tmp_path, "D", [JOINED_ROW] * 3 + spare, donor_chain())
    survey = ms.run_survey(tmp_path, CATALOG)
    dataset = survey.datasets[0]
    assert dataset.compact_rows == 6
    assert dataset.reach.files == 3
    assert dataset.filled(ms.JOIN_DONOR) == 3  # more rows than the walk reaches files
    assert dataset.reach.transitive_donor_rate > dataset.rate(ms.JOIN_DONOR)
    assert any("#337" in c[0] for c in ms.contradictions(survey))


def test_under_the_bar_is_not_reported_as_none(tmp_path):
    # A dimension-carrying table naming 1 of 20 files scores 5% — a "no" verdict,
    # which is a band below the bar, not a zero. The table prints the 5%, so a
    # sentence claiming the dataset has none would contradict it.
    write_sidecar(tmp_path, {"D": 20})
    write_manifests(
        tmp_path,
        "D",
        [{"files.file_id": f"f{i}"} for i in range(20)],
        [anvil_file(f"f{i}") for i in range(20)] + [("hifi", {"hifi_id": "s", "path": "f1"})],
    )
    report = ms.render_report(ms.run_survey(tmp_path, CATALOG))
    assert "No dimension-carrying submitter table at all" not in report
    assert "under the 10% bar" in report


# --- the reader this leans on -------------------------------------------------


def test_verbatim_reader_raises_on_a_line_it_cannot_use(tmp_path):
    path = tmp_path / "broken.jsonl"
    path.write_text('{"type": "anvil_file", "value": {"file_id": "f1"}}\nnot json\n')
    with pytest.raises(ValueError, match="line 2"):
        list(iter_verbatim_entities(path))


def test_verbatim_reader_raises_on_a_type_that_is_not_a_name(tmp_path):
    # A null `type` would reach every caller that asks whether the name starts
    # with `anvil_`; it is refused here, where the line number is still known.
    path = tmp_path / "untyped.jsonl"
    path.write_text('{"type": null, "value": {"file_id": "f1"}}\n')
    with pytest.raises(ValueError, match="line 1: entity type is NoneType"):
        list(iter_verbatim_entities(path))


def test_verbatim_reader_skips_blank_lines(tmp_path):
    path = tmp_path / "padded.jsonl"
    path.write_text('\n{"type": "anvil_file", "value": {"file_id": "f1"}}\n\n')
    assert [t for t, _ in iter_verbatim_entities(path)] == ["anvil_file"]
